myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sitesystem.urls')),
]

sitesystem/urls.py
from django.urls import path
from . import views

app_name = 'sitesystem'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post-detail/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('strategy-list/', views.StrategyView.as_view(), name='strategy_list'),
    path('cheatcode-list/', views.CheatcodeView.as_view(), name='cheatcode_list'),
    path('rta-list/', views.RtaView.as_view(), name='rta_list'),
    path('news-list/', views.NewsView.as_view(), name='news_list'),
    path('comment/create/<int:pk>/', views.CommentView.as_view(), name='comment_form'),
]

sitesystem/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import When, Count, Case, QuerySet

# Create your models here.
class MyPost(models.Model):

    CATEGORY = (('strategy', '攻略'),
                ('cheatcode', '裏技'),
                ('rta', 'RTA'),
                ('news', 'ニュース'))
    
    title = models.CharField(
        verbose_name = 'タイトル',
        max_length=200
        )

    content = models.TextField(
        verbose_name = '本文'
        )
    
    posted_at = models.DateTimeField(
        verbose_name = '投稿日時',
        auto_now_add=True
        )
    
    category = models.CharField(
        verbose_name = 'カテゴリ',
        max_length = 50,
        choices = CATEGORY
        )
    
    views = models.PositiveIntegerField(
        default=0
        )
    
    @staticmethod
    def with_state(user_id: int) -> QuerySet:
        return MyPost.objects.annotate(
            likes_cnt=Count('likes'),
            liked_by_me=Case(
                When(id__in=Likes.objects.filter(user_id=user_id).values(), then=1),
                default=0,
                output_field=models.IntegerField(),
            )
        )
    
    def __str__(self):
        return self.title

class Likes(models.Model):
    articles = models.ForeignKey('MyPost', on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class Comment(models.Model):
    user_name = models.CharField('名前', max_length=255, default='名無し')
    message = models.TextField('本文')
    target = models.ForeignKey(MyPost, on_delete=models.CASCADE, verbose_name='対象記事')
    created_at = models.DateTimeField('作成日', auto_now_add=True)
 
    def __str__(self):
        return self.message[:20]

sitesystem/forms.py
from django import forms
from .models import Comment

class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('target', 'created_at')

sitesystem/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from .models import MyPost, Comment
from .forms import CommentCreateForm
from django import forms

# Create your views here.
class IndexView(ListView):
    template_name = 'index.html'
    context_object_name = 'orderby_records'
    queryset = MyPost.objects.order_by('-posted_at')
    paginate_by = 4

class PostDetail(DetailView):
    template_name = 'post.html'
    model = MyPost

class StrategyView(ListView):
    template_name = 'strategy_list.html'
    model = MyPost
    context_object_name = 'strategy_records'
    queryset = MyPost.objects.filter(category='strategy').order_by('-posted_at')
    paginate_by = 2

class CheatcodeView(ListView):
    template_name = 'cheatcode_list.html'
    model = MyPost
    context_object_name = 'cheatcode_records'
    queryset = MyPost.objects.filter(category='cheatcode').order_by('-posted_at')
    paginate_by = 2

class RtaView(ListView):
    template_name = 'rta_list.html'
    model = MyPost
    context_object_name = 'rta_records'
    queryset = MyPost.objects.filter(category='rta').order_by('-posted_at')
    paginate_by = 2

class NewsView(ListView):
    template_name = 'news_list.html'
    model = MyPost
    context_object_name = 'news_records'
    queryset = MyPost.objects.filter(category='news').order_by('-posted_at')
    paginate_by = 2

class CommentView(CreateView):
    template_name = 'comment_form.html'
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        post_pk = self.kwargs['pk']
        post = get_object_or_404(MyPost, pk=post_pk)
        comment = form.save(commit=False)
        comment.target = post
        comment.save()
        return render('sitesystem:post', pk=post_pk)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(MyPost, pk=self.kwargs['pk'])
        return context


def viewer(request, post_id):
    post = get_object_or_404(MyPost, id=post_id)
    post.views += 1 #閲覧数をインクリメント
    post.save()
    return render(request, 'index.html', {'post': post})

sitesystem/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href={% static "assets/favicon.ico" %} />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static "css/styles.css" %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href={% url 'sitesystem:index' %}>ツイッター</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'sitesystem:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'sitesystem:strategy_list' %}">攻略</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'sitesystem:cheatcode_list' %}">裏技</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'sitesystem:rta_list' %}">RTA</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'sitesystem:news_list' %}">ニュース</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
         {% block header %}{% endblock %}
        <!-- Main Content-->
         {% block contents %}{% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://twitter.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.facebook.com/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://github.co.jp/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; My Website 2024</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static "js/scripts.js" %}></script>
    </body>
</html>

sitesystem/templates/cheatcode_list.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    {% block title %}ツイッター - 裏技{% endblock %}
        <!-- Navigation-->
        <!-- Page Header-->
         {% block header %}
        <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>ツイッター</h1>
                            <span class="subheading">裏技カテゴリの記事一覧</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Main Content-->
         {% block contents %}
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">

                    {% for record in cheatcode_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'sitesystem:post_detail' record.pk %}">
                            <h2 class="post-title">{{record.title}}</h2>
                            <h3 class="post-subtitle">
                                <span style="font-size : 14pt">{{record.content|truncatechars:50}}</span>
                            </h3>
                        </a>
                        <p class="post-meta">
                            <a href="#!">ツイッター</a>
                            {{record.posted_at}}に投稿／カテゴリ:
                            {{record.category}}
                        </p>
                        
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />

                    {% endfor %}
                    <!-- Pager-->
                     {% include 'pagination.html' %}
                </div>
            </div>
        </div>
        {% endblock %}

sitesystem/templates/comment_form.html
<div class="container col-lg-6 offset-lg-3">
    <h2 class="titleline"><span>{{ record.title }}</span></h2>
    <form action="" method="POST" id="comment-form">

        {{ form.non_field_errors }}

        {% for field in form %}
        <div class="field">
            {{ field.label_tag }}
            {% render_field field class="form-control" %}

            {{ field.errors }}
        </div>
        {% endfor %}
        {% csrf_token %}

        <div class="row my-3">
            <button type="submit" class="btn btn-success col-3 offset-2">投稿する</button>
            <a class="btn btn-danger col-3 offset-2" href="{% url 'sitesystem:post' post.pk %}">キャンセル</a>
        </div>
    </form>
</div>

sitesystem/templates/index copy 5.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    {% block title %}ツイッター{% endblock %}
        <!-- Navigation-->
        <!-- Page Header-->
         {% block header %}
        <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>ツイッター</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Main Content-->
         {% block contents %}
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">

                    {% for record in orderby_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'sitesystem:post_detail' record.pk %}">
                            <h2 class="post-title">{{record.title}}</h2>
                            <h3 class="post-subtitle">
                                <span style="font-size : 14pt">{{record.content|truncatechars:50}}</span>
                            </h3>
                        </a>
                        <p class="post-meta">
                            <a href="#!">ツイッター</a>
                            {{record.posted_at}}に投稿／カテゴリ:
                            {{record.category}}
                        </p>
                        
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />

                    {% endfor %}
                    <!-- Pager-->
                     {% include 'pagination.html' %}
                </div>
            </div>
        </div>
        {% endblock %}

sitesystem/templates/index.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    {% block title %}ツイッター{% endblock %}
        <!-- Navigation-->
        <!-- Page Header-->
         {% block header %}
        <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>ツイッター</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Main Content-->
         {% block contents %}
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">

                    {% for record in orderby_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'sitesystem:post_detail' record.pk %}">
                            <h2 class="post-title">{{record.title}}</h2>
                            <h3 class="post-subtitle">
                                <span style="font-size : 14pt">{{record.content|truncatechars:50}}</span>
                            </h3>
                        </a>
                        <p class="post-meta">
                            <a href="#!">ツイッター</a>
                            {{record.posted_at}}に投稿／カテゴリ:
                            {{record.category}}
                        </p>
                        
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />

                    {% endfor %}
                    <!-- Pager-->
                     {% include 'pagination.html' %}
                </div>
            </div>
        </div>
        {% endblock %}

sitesystem/templates/news_list.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    {% block title %}ツイッター - ニュース{% endblock %}
        <!-- Navigation-->
        <!-- Page Header-->
         {% block header %}
        <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>ツイッター</h1>
                            <span class="subheading">ニュースカテゴリの記事一覧</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Main Content-->
         {% block contents %}
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">

                    {% for record in news_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'sitesystem:post_detail' record.pk %}">
                            <h2 class="post-title">{{record.title}}</h2>
                            <h3 class="post-subtitle">
                                <span style="font-size : 14pt">{{record.content|truncatechars:50}}</span>
                            </h3>
                        </a>
                        <p class="post-meta">
                            <a href="#!">ツイッター</a>
                            {{record.posted_at}}に投稿／カテゴリ:
                            {{record.category}}
                        </p>
                        
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />

                    {% endfor %}
                    <!-- Pager-->
                     {% include 'pagination.html' %}
                </div>
            </div>
        </div>
        {% endblock %}

sitesystem/templates/pagination.html
<ul class="pagination" style="justify-content:center">

    {% if page_obj.has_previous %}

    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}

        <li class="page-item active">
            <span class="page-link">{{ num }}</span>
        </li>

        {% else %}

        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}

    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>

sitesystem/templates/post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ツイッター{% endblock %}
        <!-- Page Header-->
         {% block header %}
        <header class="masthead" style="background-image: url({% static 'assets/img/post-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>{{object.title}}</h1>
                            <h2 class="subheading">{{object.content|truncatechars:30}}</h2>
                            <span class="meta">
                                <a href="{% url 'sitesystem:index' %}">ツイッター</a>
                                {{object.posted_at}}に投稿／カテゴリ:
                                {{object.category}}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Post Content-->
         {% block contents %}
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>{{object.content}}</p>
                    </div>
                </div>
            </div>
        </article>

        <hr>
        
        <h3 class="comment-title">コメント</h3>

        {% for comment in object.comment_set.all %}
        <div class="comment-list">
            <div class="border-bottom">{{ comment.user_name }} {{ comment.created_at }}</div>
            <div class="mt-2">{{ comment.message | linebreaks | urlize }}</div>
        </div>
        {% empty %}
        <p>コメントはありません</p>
        <button type="submit" class="btn btn-success col-3 offset-2"><a href="{% url 'sitesystem:comment_form' post.pk %}">投稿する</a></button>
        {% endfor %}

        {% endblock %}

sitesystem/templates/rta_list.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    {% block title %}ツイッター - RTA{% endblock %}
        <!-- Navigation-->
        <!-- Page Header-->
         {% block header %}
        <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>ツイッター</h1>
                            <span class="subheading">RTAカテゴリの記事一覧</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Main Content-->
         {% block contents %}
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">

                    {% for record in rta_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'sitesystem:post_detail' record.pk %}">
                            <h2 class="post-title">{{record.title}}</h2>
                            <h3 class="post-subtitle">
                                <span style="font-size : 14pt">{{record.content|truncatechars:50}}</span>
                            </h3>
                        </a>
                        <p class="post-meta">
                            <a href="#!">ツイッター</a>
                            {{record.posted_at}}に投稿／カテゴリ:
                            {{record.category}}
                        </p>
                        
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />

                    {% endfor %}
                    <!-- Pager-->
                     {% include 'pagination.html' %}
                </div>
            </div>
        </div>
        {% endblock %}

sitesystem/templates/strategy_list.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    {% block title %}ツイッター - 攻略{% endblock %}
        <!-- Navigation-->
        <!-- Page Header-->
         {% block header %}
        <header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>ツイッター</h1>
                            <span class="subheading">攻略カテゴリの記事一覧</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Main Content-->
         {% block contents %}
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">

                    {% for record in strategy_records %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'sitesystem:post_detail' record.pk %}">
                            <h2 class="post-title">{{record.title}}</h2>
                            <h3 class="post-subtitle">
                                <span style="font-size : 14pt">{{record.content|truncatechars:50}}</span>
                            </h3>
                        </a>
                        <p class="post-meta">
                            <a href="#!">ツイッター</a>
                            {{record.posted_at}}に投稿／カテゴリ:
                            {{record.category}}
                        </p>
                        
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />

                    {% endfor %}
                    <!-- Pager-->
                     {% include 'pagination.html' %}
                </div>
            </div>
        </div>
        {% endblock %}